# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/rossy0213/retry
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run:
          name: go test
          command: |
            go test -v -race -cover -coverprofile=coverage.out ./...
      - codecov/upload:
          file: ./coverage.out